CREATE DATABASE LIBRARY
GO

CREATE LOGIN library_login WITH PASSWORD = 'Password123';
GO
CREATE USER library_user FOR LOGIN library_login;
GRANT UPDATE, INSERT, DELETE, SELECT ON DATABASE::LIBRARY TO library_user;
GO

CREATE TABLE AUTHORS (
	ID INT IDENTITY (1,1) PRIMARY KEY ,
	NAME_A VARCHAR (35),
);

CREATE TABLE GENRE (
    ID INT IDENTITY (1,1) PRIMARY KEY,
	TYPE VARCHAR (20),
);

CREATE TABLE BOOKS(
ISBN INT IDENTITY (1,1) PRIMARY KEY,
AUTHOR INT FOREIGN KEY REFERENCES AUTHORS(ID),
GENRE INT FOREIGN KEY REFERENCES GENRE(ID),
TITLE VARCHAR (30),
AMOUNT SMALLINT,
D DATE,
);


CREATE TABLE USERS(
    ID INT IDENTITY (1,1) PRIMARY KEY,
	NAME_U VARCHAR (50) NOT NULL,
	PASSWORD VARCHAR (72) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL UNIQUE,
	REGIST_DATE DATETIME,
	);
