CREATE DATABASE LIBRARY
GO

USE LIBRARY;

CREATE LOGIN library_login WITH PASSWORD = 'Password123';
GO
CREATE USER library_user FOR LOGIN library_login;
GRANT UPDATE, INSERT, DELETE, SELECT ON DATABASE::LIBRARY TO library_user;
GO

CREATE TABLE AUTHORS (
	ID INT IDENTITY (1,1) PRIMARY KEY ,
	NAME_A VARCHAR (35),
);

CREATE TABLE GENRE (
    ID INT IDENTITY (1,1) PRIMARY KEY,
	TYPE VARCHAR (20),
);

CREATE TABLE BOOKS(
    ISBN VARCHAR(20) PRIMARY KEY,
    AUTHOR_ID INT FOREIGN KEY REFERENCES AUTHORS(ID),
    TITLE VARCHAR(100),
    YEAR INT
);

CREATE TABLE AMOUNTS(
    ISBN VARCHAR(20) FOREIGN KEY REFERENCES BOOKS(ISBN),
    TOTAL INT DEFAULT 0,
    TAKEN INT DEFAULT 0,
    BOOKED INT DEFAULT 0,
    LOST INT DEFAULT 0,
);

create table BOOK_GENRES (
	BOOK_ID VARCHAR(20) FOREIGN KEY REFERENCES BOOKS(ISBN),
	GENRE_ID INT FOREIGN KEY REFERENCES GENRE(ID)
);

CREATE TABLE USERS(
    ID INT IDENTITY (1,1) PRIMARY KEY,
	NAME_U VARCHAR (50) NOT NULL,
	PASSWORD VARCHAR (72) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL UNIQUE,
	REGIST_DATE DATETIME,
	IS_BLOCKED BIT DEFAULT 0
	);

CREATE TABLE DEADLINES(
    ID_BOOK VARCHAR(20) FOREIGN KEY REFERENCES BOOKS(ISBN),
    FOR_BOOKING  INT,
	FOR_ISSUANCE INT,
	FORFEIT INT,
	);

CREATE TABLE ISSUANCE(
    ID INT IDENTITY PRIMARY KEY,
    USER_ID INT FOREIGN KEY REFERENCES USERS(ID),
    BOOK_ID VARCHAR(20) FOREIGN KEY REFERENCES BOOKS(ISBN),
    DATE_TAKEN DATETIME,
    DATE_RETURN DATETIME,
    STATUS VARCHAR(20)
);

CREATE TABLE BOOKING(
    ID INT IDENTITY PRIMARY KEY,
    USER_ID INT FOREIGN KEY REFERENCES USERS(ID),
    BOOK_ID VARCHAR(20) FOREIGN KEY REFERENCES BOOKS(ISBN),
    START_DATE DATETIME,
    END_DATE DATETIME,
    STATUS VARCHAR(20)
);

CREATE TABLE PENALTY(
    ID INT IDENTITY PRIMARY KEY,
    USER_ID INT FOREIGN KEY REFERENCES USERS(ID),
    ISSUANCE_ID INT FOREIGN KEY REFERENCES ISSUANCE(ID),
    AMOUNT DECIMAL(10,2),
    DEADLINE DATETIME,
    IS_PAID BIT DEFAULT 0
);

CREATE TABLE ADMINS(
    ID INT IDENTITY PRIMARY KEY,
    NAME_A VARCHAR(50),
    LOGIN VARCHAR(50) UNIQUE,
    PASSWORD VARCHAR(100),
    CREATED_AT DATETIME DEFAULT GETDATE()
);

ALTER TABLE USERS
ADD ROLE VARCHAR(20) DEFAULT 'user'; -- user/admin

GO
  
CREATE VIEW STATISTICS_VIEW AS
SELECT 
    COUNT(*) AS BOOKS_TAKEN
FROM ISSUANCE;

GO

CREATE INDEX idx_books_title ON BOOKS(TITLE);
CREATE INDEX idx_books_author ON BOOKS(AUTHOR_ID);

ALTER TABLE USERS
ADD CONSTRAINT chk_email CHECK (EMAIL LIKE '%@%.%');
